[keybindings]
"p" = "playpause"

[theme]
primary = "light white"
secondary = "light black"
title = "#1DB954"
playing = "#1DB954"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#1DB954"
statusbar_bg = "#1DB954"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"

[credentials]
username_cmd = "echo 312vayuplc4wmomk7z4t7oara36e"
password_cmd = "pass accounts/spotify"
